version: '3'

services:
  appblorem:
    image: bapp
    build:
      dockerfile: w_app.Dockerfile
      context: .
    ports:
      - "8000:80"
    networks:
      - blorem-network
    depends_on:
      - "redisblorem"
    container_name: blorem_app
  
  schedulerblorem:    
    image: bscheduler
    build:
      dockerfile: w_scheduler.Dockerfile
      context: .    
    networks:
      - blorem-network    
    container_name: blorem_scheduler
      
  redisblorem:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - blorem-network
    container_name: blorem_cache

networks: 
    blorem-network:
        driver: bridge